<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon as Carbon;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Get Organization IDs.
        $orgIDs = DB::table('organizations')->pluck('id');
        // Get Announcement IDs.
        $annIDs = DB::table('announcements')->pluck('id');
        $faker = \Faker\Factory::create();
        
        $data = [
            [
                's_number' => '43',
                'img' => "assets/images/img/qanonAasasi.png",
                'title' => "قرداد  تیل گاز 072DXR6571 - کمیسیون مستقل نظارت برتطبیق قانون اساسی",
                'issue_address' => "delivered",
                'offer_price' => '65',
                'project_price' => '65',
                'price' => '199.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],

            [
                's_number' => '5',
                'img' => "assets/images/img/adliyee.png",
                'title' => "قرداد تیل 0012DXR4571 - وزارت عدليه",
                'issue_address' => "canceled",
                'offer_price' => '87',
                'project_price' => '87',
                'price' => '199.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '6',
                'img' => "assets/images/img/haj.png",
                'title' => "قرداد تیل 0012DXR4581 - وزارت ارشاد، حج و اوقاف",
                'issue_address' => "canceled",
                'offer_price' => '55',
                'project_price' => '55',
                'price' => '39.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '7',
                'img' => "assets/images/img/vezaratdefa.png",
                'title' => "قرداد تیل 0012DXR4531 - وزارت دفاع ملى افغانستان",
                'issue_address' => "on_hold",
                'offer_price' => '99',
                'project_price' => '99',
                'price' => '39.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '8',
                'img' => "assets/images/img/sehad-ama.png",
                'title' => "قرداد تیل 0012DXR4511 - وزارت  صحت عامه",
                'issue_address' => "canceled",
                'offer_price' => '91',
                'project_price' => '91',
                'price' => '39.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '10',
                'img' => "assets/images/img/moe_final_logo_png_0.png",
                'title' => "قرداد تیل 0012DXR4551 - وزارت اقتصاد",
                'issue_address' => "canceled",
                'offer_price' => '64',
                'project_price' => '64',
                'price' => '39.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '1',
                'img' => "assets/images/img/image (2).png",
                'title' => "قرداد تیل 0052DXD4591 - وزارت کاروامور اجتماعی",
                'issue_address' => "on_hold",
                'offer_price' => '97',
                'project_price' => '97',
                'price' => '69.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '2',
                'img' => "assets/images/img/image (1).png",
                'title' => "قرداد تیل دیزل 0212DXR4771 - وزارت امور زنان",
                'issue_address' => "delivered",
                'offer_price' => '83',
                'project_price' => '83',
                'price' => '69.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '3',
                'img' => "assets/images/img/image (3).jpg",
                'title' => "قرداد تیل پطرول 0032DXR4871 - وزارت امور داخله",
                'issue_address' => "canceled",
                'offer_price' => '57',
                'project_price' => '57',
                'price' => '199.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '9',
                'img' => "assets/images/img/image (1).jpg",
                'title' => "قرداد تیل دیزل 0012DXR3571 - وزارت معارف",
                'issue_address' => "delivered",
                'offer_price' => '52',
                'project_price' => '52',
                'price' => '39.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
            [
                's_number' => '19',
                'img' => "assets/images/img/vezarat-ab.png",
                'title' => "قرداد تیل دیزل 0012DXR3571 - وزارت انرژی و آب",
                'issue_address' => "delivered",
                'offer_price' => '52',
                'project_price' => '52',
                'price' => '39.99',
                'offer_date' => Carbon::now(),
                'close_date' =>Carbon::now(),
                'duration' => '2',
                'announce_id' => $faker->randomElement($annIDs),
                'organization_id' => $faker->randomElement($orgIDs),
                'source_address' => 'کابل', 
                'auth_number' => '3979',
                'issue_date' => Carbon::now(),
            ],
        ];
        
        // Insert the data to this table
        DB::table('projects')->insert($data);
    }
}
